shedbuilt-base-layout --mode bootstrap --compression none
linux-headers --mode bootstrap
man-pages --mode bootstrap
glibc --mode bootstrap
tzdata --mode bootstrap
zlib --mode bootstrap
file --mode bootstrap
readline --mode bootstrap
m4 --mode bootstrap
bc --mode bootstrap
binutils --mode bootstrap
gmp --mode bootstrap
mpfr --mode bootstrap
mpc --mode bootstrap
gcc --mode bootstrap
bzip2 --mode bootstrap
pkg-config --mode bootstrap
ncurses --mode bootstrap
attr --mode bootstrap
acl --mode bootstrap
libcap --mode bootstrap
sed --mode bootstrap
shadow --mode bootstrap
psmisc --mode bootstrap
iana-etc --mode bootstrap
bison --mode bootstrap
flex --mode bootstrap
grep --mode bootstrap
bash --mode bootstrap
libtool --mode bootstrap
gdbm --mode bootstrap
gperf --mode bootstrap
expat --mode bootstrap
inetutils --mode bootstrap
perl --mode bootstrap
perl_error --mode bootstrap
perl_xml-parser --mode bootstrap
intltool --mode bootstrap
autoconf --mode bootstrap
automake --mode bootstrap
xz --mode bootstrap
kmod --mode bootstrap
gettext --mode bootstrap
libelf --mode bootstrap
libffi --mode bootstrap
python3 --mode bootstrap
ninja --mode bootstrap
meson --mode bootstrap
systemd --mode bootstrap
procps-ng --mode bootstrap
e2fsprogs --mode bootstrap
coreutils --mode bootstrap
diffutils --mode bootstrap
gawk --mode bootstrap
findutils --mode bootstrap
groff --mode bootstrap
less --mode bootstrap
gzip --mode bootstrap
iproute2 --mode bootstrap
kbd --mode bootstrap
libpipeline --mode bootstrap
make --mode bootstrap
patch --mode bootstrap
dbus --mode bootstrap
util-linux --mode bootstrap
man-db --mode bootstrap
tar --mode bootstrap
texinfo --mode bootstrap
which --mode bootstrap
libusb --mode bootstrap
alarm-fake-hwclock --mode bootstrap
vim --mode bootstrap
nano --mode bootstrap
shedbuilt-system-config --mode bootstrap
python --mode bootstrap
pcre --mode bootstrap
swig --mode bootstrap
libfdt --mode bootstrap
u-boot --mode bootstrap
openssl --mode bootstrap
openssh --mode bootstrap
wget --mode bootstrap
curl --mode bootstrap
ca-certs --mode bootstrap
screen --mode bootstrap
git --mode bootstrap
sudo --mode bootstrap
shedbuilt-shell-config --mode bootstrap
linux --mode bootstrap
shedmake --mode bootstrap
